Repository DreamWeave-MP/CoreScripts, pull requests merged in 2023-10, with the labels that each got.

#32 EMMY(animHelper): Create emmylua annotations for animHelper
  scripts/animHelper.lua
  scripts/serverCore.lua
  scripts/types.lua
Labels: documentation, enhancement

#35 EMMY(Color.lua): Create annotations for color.lua
  scripts/color.lua
Labels: documentation, enhancement

#37 Doc(wrapper): Annotate tes3mp wrapper
  scripts/wrapper.lua
Labels: documentation, enhancement

#36 Fix(vectors): Proposed resolution to DW #19 , which replaces length operator overrides with length metamethods
  scripts/vectors.lua
Labels: enhancement

#33 Doc(clientVariableScopes): Experimental annotations for clientVariableScopes
  scripts/clientVariableScopes.lua
Labels: documentation, enhancement

#47 feat(tableHelper): add getEntryInTableByValue
  lib/lua/tableHelper.lua
Labels: bug, enhancement

#41 Feat(server): Tracebacks on crashes
  scripts/serverCore.lua
  scripts/wrapper.lua
Labels: enhancement
